theme: jekyll-theme-slate
show_downloads: true
github:
  zip_url: https://github.com/anthony-nouy/ApproximationToolbox/zipball/master
  tar_url: https://github.com/anthony-nouy/ApproximationToolbox/tarball/master
